version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astro-app
    volumes:
      - .:/usr/src/app
    ports:
      - '4321:4321'
    stdin_open: true
    tty: true
